# Enhanced GoReleaser Configuration Template
# Merges cli-template simplicity with gofs advanced features
# Compatible with CLI template structure and customization workflow

version: 2

# TEMPLATE_PLACEHOLDER: Will be replaced by customize.sh
project_name: mycli

before:
  hooks:
    # Clean up dependencies before build
    - go mod tidy
    # OPTIONAL: Add additional pre-build hooks
    # - make clean
    # - go generate ./...

builds:
  - id: mycli
    # TEMPLATE_PLACEHOLDER: Main package path (compatible with cli-template structure)
    main: ./main.go
    # TEMPLATE_PLACEHOLDER: Binary name (will be replaced by customize.sh)
    binary: mycli
    env:
      # Disable CGO for static linking
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Exclude arm64 Windows (not supported by Go)
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      # Strip debug info and reduce binary size
      - -s -w
      # TEMPLATE_PLACEHOLDER: Compatible with cli-template variable structure
      - -X github.com/samzong/cli-template/cmd.Version={{.Version}}
      - -X github.com/samzong/cli-template/cmd.BuildTime={{.Date}}
      # OPTIONAL: Add more build-time variables
      # - -X github.com/samzong/cli-template/cmd.Commit={{.Commit}}
      # - -X github.com/samzong/cli-template/cmd.BuiltBy=goreleaser

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      # Include essential files
      - README.md
      - LICENSE
      # OPTIONAL: Include additional files
      # - CHANGELOG.md
      # - docs/**/*

# Enhanced Docker support (OPTIONAL - can be disabled)
dockers:
  - image_templates:
      - "ghcr.io/samzong/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/samzong/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/samzong/{{ .ProjectName }}"
      - "--platform=linux/amd64"

  - image_templates:
      - "ghcr.io/samzong/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/samzong/{{ .ProjectName }}:latest-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/samzong/{{ .ProjectName }}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/samzong/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/samzong/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/samzong/{{ .ProjectName }}:{{ .Version }}-arm64"

  - name_template: "ghcr.io/samzong/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/samzong/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/samzong/{{ .ProjectName }}:latest-arm64"

# Enhanced Homebrew integration with conflict prevention
brews:
  - name: mycli
    # TEMPLATE_PLACEHOLDER: Tap repository (will be replaced by customize.sh)
    repository:
      owner: samzong
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      # Create PR instead of direct push to prevent conflicts
      pull_request:
        enabled: true
    # TEMPLATE_PLACEHOLDER: Will be replaced with project-specific path
    directory: Formula
    homepage: "https://github.com/samzong/mycli"
    description: "A CLI application built with Go"
    license: "MIT"
    # OPTIONAL: Add dependencies if needed
    # dependencies:
    #   - name: git
    # test: |
    #   system "#{bin}/mycli --version"
    # OPTIONAL: Add custom install instructions
    # install: |
    #   bin.install "mycli"

changelog:
  # Enhanced changelog configuration
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - '^refactor:'
      - '^Merge'
      - '^\[skip'

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Enhanced release configuration
release:
  # Create release notes from changelog
  header: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install samzong/tap/{{ .ProjectName }}
    ```

    ### Direct Download
    Download the appropriate binary for your platform from the assets below.

    ### Docker
    ```bash
    docker run --rm ghcr.io/samzong/{{ .ProjectName }}:{{ .Version }}
    ```

  footer: |
    ## Verification

    All binaries are signed and checksums are available in `checksums.txt`.

    **Full Changelog**: https://github.com/samzong/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}

  # OPTIONAL: Disable release if needed during development
  # disable: true

# GitHub configuration
github_urls:
  api: https://api.github.com/
  upload: https://uploads.github.com/
  download: https://github.com/

# Build metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

# OPTIONAL: Sign releases (requires setup)
# signs:
#   - artifacts: checksum
#     args:
#       - "--batch"
#       - "--local-user"
#       - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
#       - "--output"
#       - "${signature}"
#       - "--detach-sign"
#       - "${artifact}"
